name: LobbyBlocks
version: 1.0
main: it.lobbyblocks.Main
authors: [ Axiid, Emaoh ]
depend:
  - ProtocolLib
commands:
  lobbyblocks:
    description: Main command
    aliases:
      - blocks
      - lblocks
